### ISSUE TITLE
Login form - In page or at top?

### ISSUE THREAD

**Issue by Phrancis** [Cardshifter/HTML-Client#18]
Tinkering around with Bootstrap and the little form we had so far, I came up with two simple designs, and just wanted to see which would be best.

**1) Form inside the page**

![navbar1](https://cloud.githubusercontent.com/assets/8539648/9096892/2679272e-3b8e-11e5-90c6-4fcfa7ce7b54.PNG)

- Pros: Easy to add/remove fields and preserve the layout. 
- Cons: Takes up page real estate, and will have to be hidden after login.

**2) Form at the top**

![navbar2](https://cloud.githubusercontent.com/assets/8539648/9096946/6b015e5c-3b8e-11e5-9a14-72671778400e.PNG)

- Pros: Leaves plenty of room for page content and does not necessarily have to be hidden after login.
- Cons: More difficult to add more fields, as widths have to be adjusted accordingly.

**Comment by SirPython** [comment]
<h1>For option 1</h1>

I think the login page should stay as a page because, what is going to go beneath that top-bar? It wouldn't make sense to put the game lobby down there because the user will have not logged in yet, and it wouldn't make sense to put an actual game screen down there because the user would have not yet entered a game.

However, it could possible be [repurposed](https://github.com/Cardshifter/HTML-Client/issues/17).

<hr>

<h1>For option 2</h1>

If we were to create a [welcome page](http://chat.stackexchange.com/transcript/message/23241066#23241066) (which you did disagree with), then this would be perfect: if the user doesn't want to immediately log in, they can explore the other things on the page.

**Comment by Phrancis** [comment]
One extra detail: There is also the option of showing/hiding stuff in the top bar depending on whether or not the user is logged in.

**Comment by Phrancis** [comment]
Looks like this will remain in-page for the foreseeable future.
