### ISSUE TITLE
Sort and filter deck builder

### ISSUE THREAD

**Issue by Zomis** [Cardshifter/HTML-Client#73]
There are many cards to choose from, it would help if it would be possible to sort them and filter them.

**Comment by SirPython** [comment]
I like the idea of sorting. Perhaps, at the top, we could has a miniature form: "Sort by..." with a drop down list of different sorting methods (by attack, by health, etc).

**Comment by Zomis** [comment]
Another option might be to make the table headers clickable and have them trigger a sort.

**Comment by SirPython** [comment]
I found that using Angular's `orderBy` was a little difficult because the values being checked are of the `properties` property, with the exception of the `max` property, which just makes things a lot more difficult.

A possible solution would be to create a function that will return an object of all the properties available for sorting right at the "top level" of the object. This function would take a card object as a parameter.

Or, if this becomes too complicated, a different way to do it would be to have a `$scope.$watch` on the `ng-model` that holds the value to be sorting by, which will then call a function for sorting the table.

**Comment by Zomis** [comment]
Sorting done, filtering not done. Reopen if filtering is wanted.
