### ISSUE TITLE
Refresh creates blank users

### ISSUE THREAD

**Issue by SirPython** [Cardshifter/HTML-Client#92]
Right now, every time the "refresh" button is clicked in the server stats section, a new "user" is created that exists as long as the user keeps the client open.

This "user" has no name, but can be seen in the lobby:

![The users list](http://i.imgur.com/uzsTCyF.png)

**Comment by Zomis** [comment]
This is likely because of two reasons:

1. When pressing the "Refresh" button, the connection is not closed after getting response from the server. (which should be fixed in the HTML Client)
2. The server sends out user information messages even for users that are not logged in (which is a server issue)
